# Generated by Django 4.2.3 on 2023-07-20 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=100)),
                ('device_type', models.CharField(max_length=100)),
                ('device_mac_address', models.CharField(max_length=17)),
                ('device_manufacturer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TimestampedData',
            fields=[
                ('timestamped_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('health_data', models.FloatField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bluetooth_data_app.device')),
            ],
        ),
    ]
